---
- name: Apply gRPC configs to XRd DevNet Sandbox.
  hosts: xr
  gather_facts: false

  vars:
    ansible_command_timeout: 60
    # Disable platform detection to avoid 'show inventory' command
    ansible_network_os: cisco.iosxr.iosxr
    ansible_iosxr_use_proxy: false

  tasks:
    - name: Enable gRPC
      cisco.iosxr.iosxr_config:
        lines:
          - grpc
        backup: no

    - name: Configure gRPC parameters
      cisco.iosxr.iosxr_config:
        lines:
          - port 57777
          - no-tls
        parents: grpc
        backup: no
